### ISSUE TITLE
pyang doesn''t see data in draft-ietf-i2rs-yang-network-topo-00 model

### ISSUE THREAD

**Issue by paulnice** [mbj4668/pyang#131]
Hello,

I've found that pyang doesn't see any data nodes in yang models defined here  - http://tools.ietf.org/html/draft-ietf-i2rs-yang-network-topo-00 
But all validations pass just ok.

Output from the current pyang
ps@lab01:~/ietf-network$ pyang -f sample-xml-skeleton ietf-network-topology.yang 
<?xml version='1.0' encoding='UTF-8'?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" />

ps@lab01:~/ietf-network# yang2dsdl ietf-network-topology.yang 
== Generating RELAX NG schema './ietf-network-topology-data.rng'
Data model defines no data.

**Comment by llhotka** [comment]
Module ietf-network-topology augments ietf-network, so you have to include *both* module on the command line because otherwise the target node for the augment isn't present in the data model and the augment  cannot be performed. So try
```
$ pyang -f sample-xml-skeleton ietf-network-topology.yang ietf-network.yang
```
and
```
$ yang2dsdl ietf-network-topology.yang ietf-network.yang
```
See also [tutorial](https://github.com/mbj4668/pyang/wiki/Tutorial#yang-data-model)

**Comment by paulnice** [comment]
Thanks for the information. That was unclear for me, because I think we already imported that ietf-network.yang in ietf-network-topology.yang.
