### ISSUE TITLE
ClassDiagram.png

### ISSUE THREAD

**Issue by joanlandry** [mbj4668/pyang#258]
Is there any avialable documentation on how to create a class diagram.png file such as ClassDiagram.png

**Comment by svallin** [comment]
https://github.com/mbj4668/pyang/wiki/UMLOutput

**Comment by joanlandry** [comment]
where on that page are the instructions to get a class diagram like the one in classDiagram.png?
The only output I am able to get when I do pyang -f uml -o schema.uml  ensemble-schema.yang  --uml-no=stereotypes,annotation,typedef   --uml-title=schema
java -jar platnum.jar schema/uml
is a .png file that looks like the one on the web page https://github.com/mbj4668/pyang/wiki/UMLOutput
which is not the same the type of diagram as shown in classDiagram.png

**Comment by svallin** [comment]
hm, sorry I am lost, can you attach the png you are referring to?

**Comment by joanlandry** [comment]
it is located here:
https://github.com/mbj4668/pyang/tree/master/doc/img

![classdiagram 1](https://cloud.githubusercontent.com/assets/20564647/17930322/97512ce8-69d3-11e6-87e0-4b60dcafe641.png)

**Comment by svallin** [comment]
ah, that one…
I have removed an attempt for an XMI plugin, should have removed this png
XMI turned out to be a very broken interchange standard for UML tools.
Try XMI yourself between two UML tools from different vendors.
This png was a screen dump from ArgoUML which I got to read my pyang -xmi output
But I removed the plugin, impossible to maintain…

pyang -f uml will give you a hard-coded png
pyang -f omni will give you a diagram you can tweak, layout, coloring, remove snippets etc

These are the two UML pyangs I have continued with, they work...

**Comment by joanlandry** [comment]
thanks for the info
