### ISSUE TITLE
json response has prefix instead of module name for anyxml yang node type

### ISSUE THREAD

**Issue by abhijitbhalekar** [mbj4668/pyang#270]
Based on my understanding of the RFC 7951, this seems to be not an issue but still needs confirmation. 
Observation is as follows, 
A netconf response (yang based) which contains data with yang type as anyxml if passed through json converter, is not attaching module-name as given in the namespace as it does with other yang types. 

Let me know if the issue is not clear.

**Comment by mbj4668** [comment]
Hi,  I don't understand this issue.  Is it really a pyang issue?

**Comment by abhijitbhalekar** [comment]
Thanks for taking a look at this issue. 
Yes, looks like pyang issue (or may not be an issue, just clarification required). 

Following are some more details,
A yang based xml has some part with "anyxml" yang node type. If passed through pyang json converter , it gives wrong output for the contents in "anyxml" yang node. Usually non "anyxml" data content is converted properly by replacing pre-fix with module names but when processing "anyxml" contents it is not doing so.

Is it expected behavior?  OR is it a issue to be fixed?

Hope it is clear now. If not, let me know again or ask specific question or suggest if missing anything.

**Comment by llhotka** [comment]
RFC 7951 just specifies what is a valid value for anyxml instances in JSON encoding, it doesn't specify any translation procedure from XML to JSON or vice versa. The XSLT stylesheet generated by **pyang** attempts some translation but you cannot expect it to be the same as for non-anyxml stuff. Note that XML namespace prefixes cannot in general be translated because anyxml instances may declare prefixes that are unrelated to YANG. It *might* be possible to change the translation algorithm so as to translate prefixes defined in YANG as usual and leave the others, but I am not sure whether it is worth doing. What's your use case for anyxml, why don't you use normal YANG data nodes?

**Comment by abhijitbhalekar** [comment]
Thanks for the clarification and suggestion. From your response, I understand that normal json translation is done on anyxml contents and not yang validated translation (by pyang json converter).

In general I too agree with your suggestion to use normal Yang nodes instead of anyxml if proper json translation is required. No special use case I think but will find out if any and let you know.

**Comment by abhijitbhalekar** [comment]
So, contents within anyxml will be translated using normal json conversion rules or yang-json standard rules? Looks like neither. Online json converter (non-yang based) gives more or less same but slightly different result. It includes "xmlns" as an element in translated json but pyang converter will not have it.

**Comment by llhotka** [comment]
As I said, the translation is **unspecified**, i.e. implementation-specific, so what the jsonxsl plugin does is just one of many possible ways of making well-form JSON from XML. An application that has specific requirements should take care about the translation itself.

**Comment by abhijitbhalekar** [comment]
My use case is as follows,
The content of anyxml node is yang data. When converted to json using pyang converter, namespace is droped and only module name stays. That is, module name without any namespace. This is incorrect, it is not well formed json.

**Comment by llhotka** [comment]
Please attach the YANG module and XML data that you want to convert.

**Comment by abhijitbhalekar** [comment]
modules.zip contains sample yang modules.
[models.zip](https://github.com/mbj4668/pyang/files/555736/models.zip)

Files included are,
abc-app.yang
abc-app-dev1.yang
abc-app-dev2.yang
sampledata.xml
abc-app-dev12.json

Converted json has an element "aapp:default". "aapp" is a prefix and not a model name. So final json output is incorrect as the namespace is missing.

**Comment by abhijitbhalekar** [comment]
Any update on this issue? Are you able to reproduce it?

**Comment by llhotka** [comment]
First, *sampledata.xml* isn't a valid instance of *abc-app-dev1*. The anyxml node has to be represented as an XML element, so it needs to look like this:
```
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <aad1:cont1 xmlns:aad1="http://www.abcnt.com/ns/yang/abc-app-dev1">
    <aad1:dev>
      <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
        <aad2:cont2 xmlns:aad2="http://www.abcnt.com/ns/yang/abc-app-dev2">
          <aad2:prop1>property1</aad2:prop1>
          <aad2:prop2
              xmlns:aapp="http://www.abcnt.com/ns/yang/abc-app">aapp:default</aad2:prop2>
        </aad2:cont2>
      </rpc-reply>
    </aad1:dev>
  </aad1:cont1>
</rpc-reply>
```
But then, how is a converting tool supposed to know that the ``<rpc-reply>`` content is an instance
of *abc-app-dev2* in order to be able to convert ``aad2`` prefix to the name of this module? Note that the *abc-app-dev2* is not part of the data model. And what about the ``<rpc-reply>`` element itself?

But I think that your use case can be addressed with [schema mount](https://tools.ietf.org/html/draft-ietf-netmod-schema-mount-03), except that ``anydata`` will be used instead of ``anyxml``. I expect schema mount to be implemented in pyang really soon.

**Comment by alex4747-pub** [comment]
Just wondering Is schema-mount implemented by now?
