### ISSUE TITLE
default value on pattern error occured.

### ISSUE THREAD

**Issue by zzyyll2** [mbj4668/pyang#298]
my test.yang like this:
module test {
    namespace "urn:local:params:xml:ns:yang:test";
	prefix test;
	container Root {
		uses grpId;   
	}
	grouping grpId {
		leaf Id{
			type typeString;
			default "1";
		}
	}
    typedef typeString {
        type string{
            length "1..255";
            pattern "^[A-Za-z0-9\-_\.]+$";
        }
    }
}

when using command pyang -f yang -o test.yin test.yang
i got some error :
test.yang:11: error: the value "1" does not match its base type at test.yang:14 - pattern mismatch for the default value for pattern defined at test.yang:17

**Comment by llhotka** [comment]
Remove the anchors '^' and '$', they are not used in YANG (and XSD) regular expressions. I am not sure, maybe it works, but I would also suggest to escape the dash after "9". And finally, it's better to use single quotes so as to allow backslash escapes. That is, the pattern statement IMO should be 
```
pattern '[A-Za-z0-9\-_.]+';
```

**Comment by zzyyll2** [comment]
Sorry，i submitted the model contain escape the dash after "9",but page displays it has not 
i think it's the input edit box 's bug.
you can try it yourself.

**Comment by zzyyll2** [comment]
I have tested that YANG support the anchors '^' and '$',it means start with the character and end with the character.

**Comment by llhotka** [comment]
OK, to avoid this, mark it as code - wrap it in triple back quotes, see my previous example.

Anyway, your pattern has two problems:

1. The anchors `^` and `$` need to be removed, see [appendix F](https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#regexs) in XSD Datatypes.

1. Inside double quotes, backslash `\` can be followed only by `n`, `t`, `"` and `\`, see [sec. 6.1.3](https://tools.ietf.org/html/rfc7950#section-6.1.3) of RFC 7950. So either use single quotes as I suggested, or otherwise you have to change every backslash to `\\`.
