### ISSUE TITLE
Unable to augment extension?

### ISSUE THREAD

**Issue by abhikeshav** [mbj4668/pyang#365]
Hi,
I have the below module:
```yang
module g
{
    namespace "urn:g";
    prefix g;

    extension ac {
        argument "name";
    }

    container x
    {
      grouping test-grouping {        
        g:ac test {
              input {
                  leaf test {
                      type string;
                  }
              }
        }
      }

      uses test-grouping {
          augment "test/input" {
            leaf-list xyz {
              type int32;
            }
          }
       }
    }
}

```
Seeing the below error:
```
# pyang  g.yang 
g.yang:23: error: node g::test is not found
```

**Comment by mbj4668** [comment]
Only data nodes can be augmented.  In general, an extension may or may not define a data node - but it is bad practise and strongly recommended to NOT use extensions to define data nodes, since tools will not out-of-the-box understand this -- just like this example shows.

However, if you must do this, you can write a pyang plugin that registers this extension as a keyword that defines data nodes.
