### ISSUE TITLE
problem in matching default to string pattern

### ISSUE THREAD

**Issue by verthezpw** [mbj4668/pyang#645]
See the following model:
[example.zip](https://github.com/mbj4668/pyang/files/4850425/example.zip)

This fails to validate in pyang with:
example.yang:15: error: the value "" does not match its base type at example.yang:5 - pattern mismatch  for pattern defined at example.yang:8

The pattern seems to be valid however (according to https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#charcter-classes) and the default value "" seems to match it.

**Comment by verthezpw** [comment]
This is failing newly in pyang 2.3.0, but was working in 2.2.1 and 1.7.5.

**Comment by wlupton** [comment]
@verthezpw, I've hit what I believe to be the same underlying problem. I was about to create a new issue but then saw that you'd created this.

In investigating "my" problem I had added some debug output, and this is what I see for your example:

```
% pyang example.yang 
re.match(u'\\p{IsBasicLatin}{0,255}', u'')
  -> None
example.yang:15: error: the value "" does not match its base type at example.yang:5 - pattern mismatch  for pattern defined at example.yang:8
```

Why doesn't it match? Because pyang is (now) using Python re.match, and Python regexes don't support `\p{xxx}` sequences. So this is being taken literally and that's why it doesn't match.

This is the python2 behavior. When I first hit this I was using python3, and this crashes, because from python 3.6 onwards, invalid sequences such as `\p` are errors.

```
% python3 ../mbj4668/bin/pyang example.yang 
re.match('\\p{IsBasicLatin}{0,255}', '')
Traceback (most recent call last):
  File "../mbj4668/bin/pyang", line 533, in <module>
    run()
...
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_parse.py", line 507, in _parse
    code = _escape(source, this, state)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_parse.py", line 402, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \p at position 0
```

"My" problem shows up with this YANG:

```
module pattern-bug {
  namespace "urn:pattern-bug";
  prefix "pattern-bug";

  import ietf-inet-types {
    prefix inet;
  }

  leaf ipv4-address {
    type inet:ipv4-address;
    default "0.0.0.0";
  }
}
```

Unfortunately, I think that PR #635 is responsible for the problem. XSD and python regexes aren't the same, so the python re module can't be used. The original bug #587 problem must have been something else (an lxml problem?).

**Comment by fredgan** [comment]
Yes, seems it is. I will revert the current solution.

I hate so many differences among all the different implements for regular expression.

**Comment by fredgan** [comment]
![](https://www.johndcook.com/perl-python-emacs.png)

Python re library don't recognize `\p{}` and so on.

**Comment by fredgan** [comment]
@wlupton Hi， I find the third-party lib `regex` can fix this, but I'm not sure if it deserves to add another lib to pyang. How do you think about it?

**Comment by mbj4668** [comment]
@fredgan we MUST use xsd regexp engine.  We cannot use builtin re.

**Comment by fredgan** [comment]
Okay, I have reverted #635

**Comment by verthezpw** [comment]
I've verified that this is fixed, thanks!
