### ISSUE TITLE
Confusion about "--lint"

### ISSUE THREAD

**Issue by wenovus** [mbj4668/pyang#691]
pyang's default behaviour is to validate a YANG module:
```
$ pyang --help
Usage: pyang [options] [<filename>...]

Validates the YANG module in <filename> (or stdin), and all its dependencies
```

There is also a `--lint` flag:
`--lint                Validate the module(s) according to RFC 8407rules.`

Does this mean pyang's behaviour validates a subset of RFC 8407 rules? What's the difference between the two validation behaviours? Thanks.

**Comment by fredgan** [comment]
Hi Wenbo @wenovus 

RFC8407 defines a Best Practice of YANG Model.
For example, since the `config true` is default for nodes, this substatement is unnecessary. RFC8407 defines a rule for this.
There are many other rules.

Pyang will check all the rules in the RFC8407 if `--lint` included.

The default validates are checked both in both ways. If `--lint` included, the RFC8407 rules are checked by extra.

**Comment by wenovus** [comment]
I see, so `--lint` does a more comprehensive check of RFC8407?

**Comment by fredgan** [comment]
@wenovus YES, it is.
